spring:
  datasource:
    url: jdbc:h2:mem:field_dev;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  header: Authorization
  secret: fieldproject
  token-validity-in-seconds: 3600000

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.tutorial.spring.security.jwt.dto